### PR TITLE
Support for chatMessages, SayText and SayText2

### PR DESCRIPTION
**Pull request by Fmestre96**
Compiled chatMessages, SayText and SayText2 into a Chat Object for the output of the parse function

### CODE REVIEW

**Comment by JanEricNitschke** [comment]
This looks pretty nice already. I will try to add the supporting structure into the python part, including the types.

**Comment by JanEricNitschke** [comment]
I just ran it over one of my faceit games and im not sure yet that i fully understand what `isChat` and `isChatAll` do

```
"chatMessages": [
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] Available commands:",
   "tick": 126,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !gg to launch a forfeit vote during the match",
   "tick": 126,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !report to report a teammate",
   "tick": 126,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] Available commands:",
   "tick": 2046,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !gg to launch a forfeit vote during the match",
   "tick": 2046,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !report to report a teammate",
   "tick": 2046,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0007[FACEIT^] 2 minutes left to join the server.",
   "tick": 2050,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] Available commands:",
   "tick": 3966,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !gg to launch a forfeit vote during the match",
   "tick": 3966,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !report to report a teammate",
   "tick": 3966,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] Available commands:",
   "tick": 5886,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !gg to launch a forfeit vote during the match",
   "tick": 5886,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !report to report a teammate",
   "tick": 5886,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] Available commands:",
   "tick": 7806,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !gg to launch a forfeit vote during the match",
   "tick": 7806,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !report to report a teammate",
   "tick": 7806,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] The match will start in 15 seconds!",
   "tick": 9595,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] Available commands:",
   "tick": 9726,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !gg to launch a forfeit vote during the match",
   "tick": 9726,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004- !report to report a teammate",
   "tick": 9726,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] KNIFE!",
   "tick": 11508,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] KNIFE!",
   "tick": 11508,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] KNIFE!",
   "tick": 11508,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": "ghgg",
   "tick": 16158,
   "params": [
    "edizzy",
    "ghgg",
    "",
    ""
   ],
   "isChat": true,
   "isChatAll": true,
   "type": "SayText2"
  },
  {
   "steamID": 76561198303807843,
   "text": "ghgg",
   "tick": 16158,
   "params": null,
   "isChat": true,
   "isChatAll": true,
   "type": "ChatMessage"
  },
  {
   "steamID": null,
   "text": " \u0004[FACEIT^] Team team_hyaliN won the knife round, hyaliN needs to !stay or !switch.",
   "tick": 16648,
   "params": null,
   "isChat": true,
   "isChatAll": false,
   "type": "SayText"
  },
  {
   "steamID": null,
   "text": "!stay",
   "tick": 17657,
   "params": [
    "hyaliN",
    "!stay",
    "",
    ""
   ],
   "isChat": true,
   "isChatAll": true,
   "type": "SayText2"
  },
  {
   "steamID": 76561197960282504,
   "text": "!stay",
   "tick": 17657,
   "params": null,
   "isChat": true,
   "isChatAll": true,
   "type": "ChatMessage"
  },
```

**Comment by Fmestre96** [comment]
Documentation regarding the difference between Chat, SayText and SayText2 can be found [here](https://github.com/markus-wa/demoinfocs-golang/blob/master/pkg/demoinfocs/events/events.go)

```// ChatMessage signals a player generated chat message.
// Since team chat is generally not recorded IsChatAll will probably always be false.
// See SayText for admin / console messages and SayText2 for raw network package data.
type ChatMessage struct {
	Sender    *common.Player
	Text      string
	IsChatAll bool
}

// SayText signals a chat message. It contains the raw
// network message data for admin / console messages.
// EntIdx will probably always be 0
// See ChatMessage and SayText2 for player chat messages.
type SayText struct {
	EntIdx    int // Not sure what this is, doesn't seem to be the entity-ID
	Text      string
	IsChat    bool // Not sure, from the net-message
	IsChatAll bool // Seems to always be false, team chat might not be recorded
}

// SayText2 signals a chat message. It just contains the raw network message.
// For player chat messages, ChatMessage may be more interesting.
// Team chat is generally not recorded so IsChatAll will probably always be false.
// See SayText for admin / console messages.
type SayText2 struct {
	EntIdx    int      // Not sure what this is, doesn't seem to be the entity-ID
	MsgName   string   // The message type, e.g. Cstrike_Chat_All for global chat
	Params    []string // The message's parameters, for Cstrike_Chat_All parameter 1 is the player and 2 the message for example
	IsChat    bool     // Not sure, from the net-message
	IsChatAll bool     // Seems to always be false, team chat might not be recorded
}```

**Comment by JanEricNitschke** [comment]
I have some slight changes and the python interface lined up on a local branch. Currently waiting to become a maintainer so i can push commits directly to your main branch/this PR (you would have to enable that if it isnt already) and then this could go in of @pnxenopoulos doesnt have any objections.

**Comment by JanEricNitschke** [comment]
Added my commits. Would be good for you and xeno to double check that everything is correct and makes sense.

**Comment by Fmestre96** [comment]
Gave this a quick try and it's working as expected!

**Comment by pnxenopoulos** [comment]
> 

I'll check once I'm home today, and will work into a new version on PyPI so we can pip install.

**Comment by Fmestre96** [comment]
Any update here? @pnxenopoulos

**Comment by pnxenopoulos** [comment]
> Any update here? @pnxenopoulos

Will update tonight and push to pypi

**Pull request merged**
