### PR TITLE
Fixing issue with player statistics when a player changed their name mid game. Adding more metrics to player statistics

### PR DESCRIPTION
**Pull request by JanEricNitschke**
Fixes https://github.com/pnxenopoulos/awpy/issues/183

### CODE REVIEW

**Comment by JanEricNitschke** [comment]
Addressed most points raised in https://github.com/pnxenopoulos/awpy/issues/182:

Added how many (0,1,2,3,4,5) kill rounds a player had as well as number of 1v(1,2,3,4,5) clutch attempts and successes.

Also added the number of traded deaths.

I also changed `all_true` to `any_true` for kast calculation because i think that more accurately describes what it is actually used for.

Lastly i moved all the stat finalizations into a singular loop instead of having one part stat to calculate/round.

**Comment by paulsnoops** [comment]
@JanEricNitschke thank you for adding these features!

**Comment by JanEricNitschke** [comment]
I know added the option to specify `CT` or `T` as `selected_side` to only consider things that happend while each player was playing on that side (like HLTV has that option)

Additionally i grouped some checks that were happening multiple times.

I am also now just taking the traded player from the trade kills `playerTradedSteamID` instead of going back to the last kill.
But i think the trade logic could be improved a bit in general. At the moment something is not considered a trade kill if there is an unrelated kill in between the death and the trade.

It is also not possible to have two players traded in one kill. Although that might actually be desired.

**Comment by JanEricNitschke** [comment]
Changing the trade logic such that ONLY the trade time matters and not whether it was also the overall kill directly before the trade.

This increases (or leaves constant) the number of trade kills/traded deaths.

An example would be in the demo currently used for testing the stats module: https://www.hltv.org/matches/2337844/astralis-vs-liquid-blast-pro-series-global-final-2019

Here device dies in the 5th round (Score 2-2) to Twist in Lobby and is subsequently traded by Magisk within 2 seconds. (Default trade time is 5 seconds)

However as dupreeh gets a kill on NAF by Vent between twists kill and death this did not previously count as a traded death for device.

https://www.youtube.com/watch?v=yfwuNphy1wA

Also note that with the current logic a player can get a trade on themselves, netting them both a trade kill and a traded death, by killing their killer with a molotov or HE. This is the case both before and after the current changes.

With this change this also leads to a discrepancy of devices KAST for that match compared to what HLTV gives while it matches before, at least for him. However, i do not know if this is because of that or due to a difference in the trade time or something else. There is another example that adds a traded death and there the trade is a bit slower.

**Comment by JanEricNitschke** [comment]
Fixed a bug and clarified the behaviour when trading enemies.

 A trade is always onto an enemy
If your teammate kills someone and then you kill them
-> that is not a trade kill for you
If you kill someone and then yourself
-> that is not a trade kill for you
  
Enemies CAN trade your own death
If you force an enemy to teamkill their mate after your death
 -> thats a traded death for you
If you force your killer to kill themselves (in their own molo/nade/fall)
-> that is a traded death for you

also added `playerTradedSide` to kill event

**Comment by pnxenopoulos** [comment]
On line 844 in `parse_demo.go`, we could condense it further by just `return inTradeWindow(killA, killB, tickRate, tradeTime)` right?

The changes to the trade logic are well-welcomed :) -- thank you for spotting this.

**Comment by pnxenopoulos** [comment]
As for how the trades match up with HLTV's, it's ok if there are discrepancies. I think as long as the logic is defensible and the results aren't too different, then it's fine. The main thing here is that trades are truly matched up to their associated kill events.

> Also note that with the current logic a player can get a trade on themselves, netting them both a trade kill and a traded death, by killing their killer with a molotov or HE. This is the case both before and after the current changes.

For me this is ok, but I can see why we may want to force a constraint that the player who killed cannot get the trade.

**Comment by paulsnoops** [comment]
Just wanted to say I've been testing these changes and I have parsed 80+ demos and the stats are all looking good, trades are certainly better now, thank you

**Comment by pnxenopoulos** [comment]
> Just wanted to say I've been testing these changes and I have parsed 80+ demos and the stats are all looking good, trades are certainly better now, thank you

Fantastic. Expect these to be rolled in today/tomorrow.

**Comment by JanEricNitschke** [comment]
Note that in the merged verison in https://github.com/pnxenopoulos/awpy/pull/208 i have changed the naming for multi-kills and clutches from `3kills` to `kills3` (similar for clutches) to play nice with TypedDicts.

**Comment by JanEricNitschke** [comment]
> On line 844 in `parse_demo.go`, we could condense it further by just `return inTradeWindow(killA, killB, tickRate, tradeTime)` right?
> 
> The changes to the trade logic are well-welcomed :) -- thank you for spotting this.

Changed that locally on the branch for the combined PR https://github.com/pnxenopoulos/awpy/pull/208.
Will wait with pushing in case there are more changes not rerun the building/testing pipeline unnecessarily.

**Pull request merged**
