### PR TITLE
Propagate map control types throughout awp

### PR DESCRIPTION
**Pull request by JanEricNitschke**
First commit propagates `TileId`. Please check that i didnt put it somewhere where it doesnt belong and that i didnt miss any where it does.

closes https://github.com/pnxenopoulos/awpy/issues/240

### CODE REVIEW

**Comment by JanEricNitschke** [comment]
I removed the TileDistanceObject now and instead made a very minor change to DistanceObject and use that instead.

And i noticed that DistanceObject could probably be replace with a dataclass instead of a typed dict. I think there are a bunch of opportunities for that. But that is pretty decent work and would also be a very breaking change as a couple of user facing functions return such typed dicts that would be better suited as dataclasses.

**Comment by JanEricNitschke** [comment]
I now also completely removed `TileNeighbors` as i switched from manually building the neighbors dict to just directly using `G.neighbors()`.

@adisujithkumar could you double check that this does not break anything? Tests pass but i dont know if every case is covered.

**Comment by adisujithkumar** [comment]
@JanEricNitschke Just pulled your branch and ran the MC notebook and everything ran as expected. Since tests are also passing, I think this PR looks good

**Review by adisujithkumar — APPROVED** [review]

**Review by adisujithkumar — DISMISSED** [review]

**Review by pnxenopoulos — CHANGES_REQUESTED** [review]
LGTM. After you fix the minor conflicts then I'll merge

**Pull request merged**
