### PR TITLE
Addressing documentation issues with some map control related functions

### PR DESCRIPTION
**Pull request by adisujithkumar**
Some map control functions have some docs related errors (outlined in [this GitHub Issue](https://github.com/pnxenopoulos/awpy/issues/279)). This commit should help fixing those errors and others I noticed.

### CODE REVIEW

**Comment by hojlund123** [comment]
Did a build of your PR and everything looks good to me! 

https://awpy-mapcontrol-docfix.readthedocs.io/en/latest/

**Review by hojlund123 — APPROVED** [review]

**Comment by hojlund123** [comment]
awpy/analytics/map_control.py:81:0: R0914: Too many local variables (16/15) (too-many-locals)

Is this a new lint btw? 

We have it configured to max 15 in pyproject

https://github.com/pnxenopoulos/awpy/blob/87167047ac88c9a425769403048e2786018296e2/pyproject.toml#L213C16-L213C16

**Comment by adisujithkumar** [comment]
Hm I don't think this is a new lint - I recall hitting this issue previously with my Map Control PR.

I think it will get fixed very soon however. I think in Jan-Eric's new type propagation PR, he removes the neighbor_info argument from `_bfs` and `_calc_frame_map_control_tile_values`. I think this should reduce the local variables a bit. My thought is that Jan-Eric's PR could be merged in first and I can take those changes and see if that fixes the lint issue. If it does, then we can go forward with this PR. If not, I can fix the local variable issue myself. Let me know what you guys think @JanEricNitschke @hojlund123

**Comment by JanEricNitschke** [comment]
Yeah, it's not a new lint. It's just that pylint is currently configured to allow basically one linter warning and still pass.

(The same warning is currently in main: https://github.com/pnxenopoulos/awpy/actions/runs/5707191025/job/15463655598#step:10:13)

But the type propagation PR does remove it anyway. I also have a CI update PR as draft that i will add some more commits to soon which changes the pylint threshold to allow 0 linter warnings in the future. This also currently has a fix for this warning but it is less elegant than he one in the type PR.

So i do not think we do not necessarily need to wait for the type PR as this warning is already in main anyway. (But the type PR should also be ready anway too)

**Review by pnxenopoulos — APPROVED** [review]
approving bc the boys approved

**Pull request merged**
