### PR TITLE
Fix map data

### PR DESCRIPTION
**Pull request by billfreeman44**
No need to guess on these as they are in `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\resource\overviews\...`

### CODE REVIEW

**Comment by JanEricNitschke** [comment]
Greatfind, maybe you could also add the values for anubis, tuscan, season while you are at it?

Now i dont know why i spend an hour trying to get these right...

**Comment by billfreeman44** [comment]
like this?

```
  cs_agency: {
    startX: -2947,
    startY: 2492,
    scale: 5.0,
    timerXPos: 512
  },
  cs_apollo: {
    startX: -2002,
    startY: -1604,
    scale: 5.03,
    timerXPos: 512
  },
  cs_climb: {
    startX: -858.5,
    startY: -4241,
    scale: 4.29,
    timerXPos: 512
  },
  cs_insertion2: {
    startX: -5129,
    startY: 3136,
    scale: 9.0,
    timerXPos: 512
  },
  cs_office: {
    startX: -1838,
    startY: 1858,
    scale: 4.1,
    timerXPos: 512
  },
  de_ancient: {
    startX: -2953,
    startY: 2164,
    scale: 5.0,
    timerXPos: 512
  },
  de_anubis: {
    startX: -2796,
    startY: 3328,
    scale: 5.22,
    timerXPos: 712
  },
  de_basalt: {
    startX: -2345,
    startY: 2391,
    scale: 4.37,
    timerXPos: 512
  },
  de_breach: {
    startX: -2950,
    startY: 2886,
    scale: 5.5,
    timerXPos: 512
  },
  de_chlorine: {
    startX: 2076,
    startY: 1272,
    scale: 5.25,
    timerXPos: 652
  },
  de_cache: {
    startX: -2000,
    startY: 3250,
    scale: 5.5,
    timerXPos: 512
  },
  de_canals: {
    startX: -2496,
    startY: 1792,
    scale: 4.0,
    timerXPos: 512
  },
  de_cbble: {
    startX: -3840,
    startY: -3072,
    scale: 6.0,
    timerXPos: 512
  },
  de_dust2: {
    startX: -2476,
    startY: 3239,
    scale: 4.4,
    timerXPos: 512
  },
  de_engage: {
    startX: -3530,
    startY: 2976,
    scale: 5.77,
    timerXPos: 512
  },
  de_grind: {
    startX: -3723,
    startY: 3026,
    scale: 5.0,
    timerXPos: 512
  },
  de_inferno: {
    startX: -2087,
    startY: 3860,
    scale: 4.9,
    timerXPos: 390
  },
  de_iris: {
    startX: -2288,
    startY: 2341,
    scale: 4.5,
    timerXPos: 512
  },
  de_mirage: {
    startX: -3230,
    startY: 1713,
    scale: 5.0,
    timerXPos: 512
  },
  de_mocha: {
    startX: -265,
    startY: 3210,
    scale: 5.0,
    timerXPos: 512
  },
  de_mutiny: {
    startX: -8275,
    startY: -1312,
    scale: 4.8,
    timerXPos: 512
  de_overpass: {
    startX: -4831,
    startY: 1781,
    scale: 5.2,
    timerXPos: 650
  },
  de_studio: {
    startX: -3248,
    startY: 2968,
    scale: 6.17,
    timerXPos: 512
  },
  de_swamp: {
    startX: -2600,
    startY: 3906,
    scale: 6.0,
    timerXPos: 512
  },
  de_train: {
    startX: -2477,
    startY: 2392,
    scale: 4.7,
    timerXPos: 512
  },
  de_tuscan: {
    startX: -5141,
    startY: 1088,
    scale: 4.85,
    timerXPos: 512
  }
```

**Comment by JanEricNitschke** [comment]
I don't know if we need all of these (or if it would hurt to have them all) and what the `timerXPos` does/means, but yeah, like that.
Also we should stick to the nomenclature that is already in the file with just `x` and `y`.

Also:
```
"de_season" : {
    "x"	:	"-1003"
    "y"	:	"2521"
    "scale"	:	"5.00"
}

```

**Comment by billfreeman44** [comment]
@JanEricNitschke I've added tuscan and anubis. I also added some instructions in the readme to make future updates easier.

I don't have the image for season handy and I don't think there is much data on that map anyways.

**Pull request closed without merging**
