### PR TITLE
Update ci

### PR DESCRIPTION
**Pull request by JanEricNitschke**
Testing out new pre-commit hook and trying to add go fmt check to go linters.

### CODE REVIEW

**Comment by JanEricNitschke** [comment]
I think i finally managed to also add the golang-ci linter into the pre-commit hooks.

**Comment by JanEricNitschke** [comment]
Also added pyright and pylint to be run as a pre-commit hook. They still have to be installed separately (because they need access to the normal environment) but now they do not have to be run manually anymore.

**Review by pnxenopoulos — APPROVED** [review]
Looks good to me. Was there a reason we had pylint running with `fail-under` at 9.99 before?

**Comment by JanEricNitschke** [comment]
That was from when i added it. I think i added it with 9.95 and then gradually increased it as i was fixing the original set of warnings. And i think when we merged the first set there was still a PR open that would fix that last bit already and so it wasnt in the original PR itself.

And then i just forgot to increase it to 10.0 afterwards.

**Pull request merged**
